// Основные магические числа
// блок price
const PRICES_FOR_PERIOD = {
  '1 месяц': [5000, 1700, 2700],
  '6 месяцев': [30000, 10200, 16200],
  '12 месяцев': [60000, 20400, 32400],
};
// блок juri
const MOBILE_WIDTH = 320;
const TABLET_WIDTH = 768;
const DESKTOP_WIDTH = 1366;
const MOBILE_SLIDES_PER_GROUP = 1;
const MOBILE_SLIDES_SPACE_BETWEEN = 290;
const TABLET_SLIDES_SPEED = 700;
const TABLET_SLIDES_PER_VIEW = 2;
const TABLET_SLIDES_SPACE_BETWEEN = 28;
const TABLET_SLIDES_PER_GROUP = 2;
const DESKTOP_SLIDES_PER_VIEW = 4;
const DESKTOP_SLIDES_PER_GROUP = 4;

// блок reviews
const COMMON_SLIDES_SPEED = 400;
const REVIEWS_MOBILE_SPACE_BETWEEN = 100;
const REVIEWS_MOBILE_WIDTH = 240;
const REVIEWS_TABLET_SPACE_BETWEEN = 700;
const REVIEWS_TABLET_WIDTH = 500;
const REVIEWS_DESKTOP_SPACE_BETWEEN = 800;
const REVIEWS_DESKTOP_WIDTH = 560;

// блок hero
const VIDEO_LINK =
'https://rutube.ru/video/a8fae0d450cfae0f88e500966f4eb40a/';
  // 'https://www.youtube.com/embed/9TZXsZItgdw?si=USUF2s1-47GvuEu-';

export { PRICES_FOR_PERIOD, MOBILE_WIDTH, TABLET_WIDTH, MOBILE_SLIDES_SPACE_BETWEEN, DESKTOP_WIDTH, MOBILE_SLIDES_PER_GROUP, TABLET_SLIDES_SPEED, TABLET_SLIDES_PER_VIEW, TABLET_SLIDES_SPACE_BETWEEN, TABLET_SLIDES_PER_GROUP, DESKTOP_SLIDES_PER_VIEW, DESKTOP_SLIDES_PER_GROUP, COMMON_SLIDES_SPEED, REVIEWS_MOBILE_SPACE_BETWEEN, REVIEWS_MOBILE_WIDTH, REVIEWS_TABLET_SPACE_BETWEEN, REVIEWS_TABLET_WIDTH, REVIEWS_DESKTOP_SPACE_BETWEEN, REVIEWS_DESKTOP_WIDTH, VIDEO_LINK };

